### ISSUE TITLE
Error en el programa que impide la descarga de archivos

### ISSUE THREAD

**Issue by Elking135** [albert04g28/clase-c#1]
Estimado/a programador/a del programa albertoag.

Me dirijo a usted para comunicarle un problema que he detectado en el programa,  del cual usted es el responsable de su desarrollo y mantenimiento. El problema consiste en que el programa no permite la descarga de archivos desde la plataforma Y, lo cual afecta gravemente a la funcionalidad y utilidad del mismo.

El error se produce al intentar descargar cualquier tipo de archivo desde la plataforma GitHub, ya sea mediante el botón de descarga o el menú contextual. Al hacerlo, el programa muestra un mensaje de error que dice: "No se puede completar la descarga. Compruebe su conexión a internet y vuelva a intentarlo". Sin embargo, la conexión a internet funciona correctamente y el problema persiste incluso después de reiniciar el programa y el ordenador.

He comprobado que el error no se produce al descargar archivos desde otras plataformas, ni al usar otros programas para acceder a la plataforma Y. Por lo tanto, deduzco que el problema está relacionado con el programa y su compatibilidad con la plataforma Github.

Este error supone un gran inconveniente para los usuarios de su programa , ya que la plataforma Github es una de las más populares y utilizadas para compartir y almacenar archivos en la nube. Además, su programa se promociona como una herramienta capaz de gestionar todo tipo de archivos desde cualquier plataforma, por lo que este fallo contradice su propósito y expectativas.

Por todo ello, le solicito que revise el código de su programa y que solucione el error lo antes posible, para que el programa pueda cumplir con su función y satisfacer las necesidades de los usuarios. Asimismo, le agradecería que me informara de las causas del error, de las medidas que va a tomar para resolverlo y del plazo estimado para su corrección.

Le agradezco su atención y colaboración. Espero su respuesta.

Atentamente,

El_king_135

**Comment by markutopio** [comment]
como asi

**Comment by albert04g28** [comment]
chupamela

**Comment by albert04g28** [comment]
por cierto si se puede descargar pq esta publico hector lo q pasa es q no sabes descargar un puto archivo

**Comment by Elking135** [comment]
Estimado/a usuario/a,

Lamento informarle de que su afirmación es errónea e infundada. El archivo que menciona no está disponible para su descarga. Le ruego que se abstenga de difundir información falsa o engañosa, ya que puede inducir a error a otros usuarios y perjudicar la reputación de esta plataforma. Le agradezco su comprensión y colaboración.

Atentamente,

El_king_135

**Comment by albert04g28** [comment]
Perdon tio. Gracias por la ayuda que me proporcionaste me di cuenta de mi error

**Comment by Elking135** [comment]
No pasa nada bro de todo se aprende, enga m voy q tengo q seguir haciendo mewing 🤫🧏🧏
